version: '3'

services:
  redis:
    image: "redis:alpine"

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A picha worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A picha beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis

  celery-flower:
    build: .
    command: celery -A picha flower --port=5555 --loglevel=info # --persistent=True
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    depends_on:
      - redis
